version: "3.8"

services:
  api:
    container_name: orena-api
    image: dhivinx/orena-api:0.0.1-local
    build:
      context: .
      dockerfile: ./.docker/api/Dockerfile.local
    env_file:
      - .env.local
    ports:
      - ${API_HTTP_PORT}:${API_HTTP_PORT}
    depends_on:
      - postgres
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/apps/api/node_modules
      - /app/apps/api/dist
      - /app/packages/config/node_modules
    restart: always

  web:
    container_name: orena-web
    image: dhivinx/orena-web:0.0.1-local
    build:
      context: .
      dockerfile: ./.docker/web/Dockerfile.local
    env_file:
      - .env.local
    ports:
      - 8080:8080
    depends_on:
      - api
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/apps/web/node_modules
      - /app/packages/config/node_modules
    restart: always

  postgres:
    container_name: orena-postgres
    image: postgres
    env_file:
      - .env.local
    ports:
      - "5433:${DATABASE_PORT}"
    volumes:
      - orena-postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    restart: unless-stopped

volumes:
  orena-postgres-data:
