version: "3.8"

services:
  api:
    container_name: orena-api
    image: dhivinx/orena-api:0.0.1
    build:
      context: .
      dockerfile: ./.docker/api/Dockerfile.prod
    env_file:
      - .env.prod
    ports:
      - ${API_HTTP_PORT}:${API_HTTP_PORT}
    depends_on:
      - postgres
    restart: always

  web:
    container_name: orena-web
    image: dhivinx/orena-web:0.0.1
    build:
      context: .
      dockerfile: ./.docker/web/Dockerfile.prod
    env_file:
      - .env.prod
    ports:
      - 8080:8080
    depends_on:
      - api
    restart: always

  postgres:
    container_name: orena-postgres
    image: postgres
    env_file:
      - .env.prod
    volumes:
      - orena-postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    restart: unless-stopped

volumes:
  orena-postgres-data:
